package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApprenticeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprenticeAllPropertiesEquals(Apprentice expected, Apprentice actual) {
        assertApprenticeAutoGeneratedPropertiesEquals(expected, actual);
        assertApprenticeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprenticeAllUpdatablePropertiesEquals(Apprentice expected, Apprentice actual) {
        assertApprenticeUpdatableFieldsEquals(expected, actual);
        assertApprenticeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprenticeAutoGeneratedPropertiesEquals(Apprentice expected, Apprentice actual) {
        assertThat(actual)
            .as("Verify Apprentice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprenticeUpdatableFieldsEquals(Apprentice expected, Apprentice actual) {
        assertThat(actual)
            .as("Verify Apprentice relevant properties")
            .satisfies(a -> assertThat(a.getStateAcademic()).as("check stateAcademic").isEqualTo(expected.getStateAcademic()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprenticeUpdatableRelationshipsEquals(Apprentice expected, Apprentice actual) {
        assertThat(actual)
            .as("Verify Apprentice relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()));
    }
}
