package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassScheduleAllPropertiesEquals(ClassSchedule expected, ClassSchedule actual) {
        assertClassScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertClassScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassScheduleAllUpdatablePropertiesEquals(ClassSchedule expected, ClassSchedule actual) {
        assertClassScheduleUpdatableFieldsEquals(expected, actual);
        assertClassScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassScheduleAutoGeneratedPropertiesEquals(ClassSchedule expected, ClassSchedule actual) {
        assertThat(actual)
            .as("Verify ClassSchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassScheduleUpdatableFieldsEquals(ClassSchedule expected, ClassSchedule actual) {
        assertThat(actual)
            .as("Verify ClassSchedule relevant properties")
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassScheduleUpdatableRelationshipsEquals(ClassSchedule expected, ClassSchedule actual) {
        assertThat(actual)
            .as("Verify ClassSchedule relationships")
            .satisfies(a -> assertThat(a.getTrimester()).as("check trimester").isEqualTo(expected.getTrimester()))
            .satisfies(a -> assertThat(a.getClassSection()).as("check classSection").isEqualTo(expected.getClassSection()));
    }
}
