package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassExceptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassExceptionAllPropertiesEquals(ClassException expected, ClassException actual) {
        assertClassExceptionAutoGeneratedPropertiesEquals(expected, actual);
        assertClassExceptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassExceptionAllUpdatablePropertiesEquals(ClassException expected, ClassException actual) {
        assertClassExceptionUpdatableFieldsEquals(expected, actual);
        assertClassExceptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassExceptionAutoGeneratedPropertiesEquals(ClassException expected, ClassException actual) {
        assertThat(actual)
            .as("Verify ClassException auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassExceptionUpdatableFieldsEquals(ClassException expected, ClassException actual) {
        assertThat(actual)
            .as("Verify ClassException relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassExceptionUpdatableRelationshipsEquals(ClassException expected, ClassException actual) {
        assertThat(actual)
            .as("Verify ClassException relationships")
            .satisfies(a -> assertThat(a.getClassSection()).as("check classSection").isEqualTo(expected.getClassSection()));
    }
}
