package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassSectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSectionAllPropertiesEquals(ClassSection expected, ClassSection actual) {
        assertClassSectionAutoGeneratedPropertiesEquals(expected, actual);
        assertClassSectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSectionAllUpdatablePropertiesEquals(ClassSection expected, ClassSection actual) {
        assertClassSectionUpdatableFieldsEquals(expected, actual);
        assertClassSectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSectionAutoGeneratedPropertiesEquals(ClassSection expected, ClassSection actual) {
        assertThat(actual)
            .as("Verify ClassSection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSectionUpdatableFieldsEquals(ClassSection expected, ClassSection actual) {
        assertThat(actual)
            .as("Verify ClassSection relevant properties")
            .satisfies(a -> assertThat(a.getSubjectName()).as("check subjectName").isEqualTo(expected.getSubjectName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassSectionUpdatableRelationshipsEquals(ClassSection expected, ClassSection actual) {
        assertThat(actual)
            .as("Verify ClassSection relationships")
            .satisfies(a -> assertThat(a.getInstructor()).as("check instructor").isEqualTo(expected.getInstructor()))
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()));
    }
}
