package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DesertionCounterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesertionCounterAllPropertiesEquals(DesertionCounter expected, DesertionCounter actual) {
        assertDesertionCounterAutoGeneratedPropertiesEquals(expected, actual);
        assertDesertionCounterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesertionCounterAllUpdatablePropertiesEquals(DesertionCounter expected, DesertionCounter actual) {
        assertDesertionCounterUpdatableFieldsEquals(expected, actual);
        assertDesertionCounterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesertionCounterAutoGeneratedPropertiesEquals(DesertionCounter expected, DesertionCounter actual) {
        assertThat(actual)
            .as("Verify DesertionCounter auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesertionCounterUpdatableFieldsEquals(DesertionCounter expected, DesertionCounter actual) {
        assertThat(actual)
            .as("Verify DesertionCounter relevant properties")
            .satisfies(a ->
                assertThat(a.getTotalGlobalAbsences()).as("check totalGlobalAbsences").isEqualTo(expected.getTotalGlobalAbsences())
            )
            .satisfies(a ->
                assertThat(a.getAccumulatedLateArrivals())
                    .as("check accumulatedLateArrivals")
                    .isEqualTo(expected.getAccumulatedLateArrivals())
            )
            .satisfies(a ->
                assertThat(a.getWorkJustificationsUsed()).as("check workJustificationsUsed").isEqualTo(expected.getWorkJustificationsUsed())
            )
            .satisfies(a -> assertThat(a.getAlertsSent()).as("check alertsSent").isEqualTo(expected.getAlertsSent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesertionCounterUpdatableRelationshipsEquals(DesertionCounter expected, DesertionCounter actual) {
        assertThat(actual)
            .as("Verify DesertionCounter relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getTrimester()).as("check trimester").isEqualTo(expected.getTrimester()));
    }
}
