package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeAllPropertiesEquals(DocumentType expected, DocumentType actual) {
        assertDocumentTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeAllUpdatablePropertiesEquals(DocumentType expected, DocumentType actual) {
        assertDocumentTypeUpdatableFieldsEquals(expected, actual);
        assertDocumentTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeAutoGeneratedPropertiesEquals(DocumentType expected, DocumentType actual) {
        assertThat(actual)
            .as("Verify DocumentType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeUpdatableFieldsEquals(DocumentType expected, DocumentType actual) {
        assertThat(actual)
            .as("Verify DocumentType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getInitials()).as("check initials").isEqualTo(expected.getInitials()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeUpdatableRelationshipsEquals(DocumentType expected, DocumentType actual) {
        // empty method
    }
}
