package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GlobalConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAllPropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertGlobalConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertGlobalConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAllUpdatablePropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertGlobalConfigurationUpdatableFieldsEquals(expected, actual);
        assertGlobalConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationAutoGeneratedPropertiesEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertThat(actual)
            .as("Verify GlobalConfiguration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationUpdatableFieldsEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        assertThat(actual)
            .as("Verify GlobalConfiguration relevant properties")
            .satisfies(a ->
                assertThat(a.getStudentJustificationDays())
                    .as("check studentJustificationDays")
                    .isEqualTo(expected.getStudentJustificationDays())
            )
            .satisfies(a ->
                assertThat(a.getInstructorResponseDays()).as("check instructorResponseDays").isEqualTo(expected.getInstructorResponseDays())
            )
            .satisfies(a ->
                assertThat(a.getLateArrivalsToFail()).as("check lateArrivalsToFail").isEqualTo(expected.getLateArrivalsToFail())
            )
            .satisfies(a ->
                assertThat(a.getMaxPostponementJustifications())
                    .as("check maxPostponementJustifications")
                    .isEqualTo(expected.getMaxPostponementJustifications())
            )
            .satisfies(a ->
                assertThat(a.getStandardTrimesterMonths())
                    .as("check standardTrimesterMonths")
                    .isEqualTo(expected.getStandardTrimesterMonths())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGlobalConfigurationUpdatableRelationshipsEquals(GlobalConfiguration expected, GlobalConfiguration actual) {
        // empty method
    }
}
