package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GradeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAllPropertiesEquals(Grade expected, Grade actual) {
        assertGradeAutoGeneratedPropertiesEquals(expected, actual);
        assertGradeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAllUpdatablePropertiesEquals(Grade expected, Grade actual) {
        assertGradeUpdatableFieldsEquals(expected, actual);
        assertGradeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeAutoGeneratedPropertiesEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeUpdatableFieldsEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeUpdatableRelationshipsEquals(Grade expected, Grade actual) {
        assertThat(actual)
            .as("Verify Grade relationships")
            .satisfies(a -> assertThat(a.getProgram()).as("check program").isEqualTo(expected.getProgram()))
            .satisfies(a -> assertThat(a.getModality()).as("check modality").isEqualTo(expected.getModality()))
            .satisfies(a -> assertThat(a.getTimeSlot()).as("check timeSlot").isEqualTo(expected.getTimeSlot()));
    }
}
