package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JustificationTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationTypeAllPropertiesEquals(JustificationType expected, JustificationType actual) {
        assertJustificationTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertJustificationTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationTypeAllUpdatablePropertiesEquals(JustificationType expected, JustificationType actual) {
        assertJustificationTypeUpdatableFieldsEquals(expected, actual);
        assertJustificationTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationTypeAutoGeneratedPropertiesEquals(JustificationType expected, JustificationType actual) {
        assertThat(actual)
            .as("Verify JustificationType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationTypeUpdatableFieldsEquals(JustificationType expected, JustificationType actual) {
        assertThat(actual)
            .as("Verify JustificationType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLimitPerTrimester()).as("check limitPerTrimester").isEqualTo(expected.getLimitPerTrimester()))
            .satisfies(a -> assertThat(a.getState()).as("check state").isEqualTo(expected.getState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationTypeUpdatableRelationshipsEquals(JustificationType expected, JustificationType actual) {
        // empty method
    }
}
