package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JustificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationAllPropertiesEquals(Justification expected, Justification actual) {
        assertJustificationAutoGeneratedPropertiesEquals(expected, actual);
        assertJustificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationAllUpdatablePropertiesEquals(Justification expected, Justification actual) {
        assertJustificationUpdatableFieldsEquals(expected, actual);
        assertJustificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationAutoGeneratedPropertiesEquals(Justification expected, Justification actual) {
        assertThat(actual)
            .as("Verify Justification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationUpdatableFieldsEquals(Justification expected, Justification actual) {
        assertThat(actual)
            .as("Verify Justification relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getEvidence()).as("check evidence").isEqualTo(expected.getEvidence()))
            .satisfies(a ->
                assertThat(a.getEvidenceContentType()).as("check evidence content type").isEqualTo(expected.getEvidenceContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationUpdatableRelationshipsEquals(Justification expected, Justification actual) {
        assertThat(actual)
            .as("Verify Justification relationships")
            .satisfies(a -> assertThat(a.getJustificationType()).as("check justificationType").isEqualTo(expected.getJustificationType()))
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()));
    }
}
