package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JustificationDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationDetailsAllPropertiesEquals(JustificationDetails expected, JustificationDetails actual) {
        assertJustificationDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertJustificationDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationDetailsAllUpdatablePropertiesEquals(JustificationDetails expected, JustificationDetails actual) {
        assertJustificationDetailsUpdatableFieldsEquals(expected, actual);
        assertJustificationDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationDetailsAutoGeneratedPropertiesEquals(JustificationDetails expected, JustificationDetails actual) {
        assertThat(actual)
            .as("Verify JustificationDetails auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationDetailsUpdatableFieldsEquals(JustificationDetails expected, JustificationDetails actual) {
        assertThat(actual)
            .as("Verify JustificationDetails relevant properties")
            .satisfies(a ->
                assertThat(a.getStateJustification()).as("check stateJustification").isEqualTo(expected.getStateJustification())
            )
            .satisfies(a -> assertThat(a.getRejectionReason()).as("check rejectionReason").isEqualTo(expected.getRejectionReason()))
            .satisfies(a -> assertThat(a.getCorrectionText()).as("check correctionText").isEqualTo(expected.getCorrectionText()))
            .satisfies(a -> assertThat(a.getCorrectionFileUrl()).as("check correctionFileUrl").isEqualTo(expected.getCorrectionFileUrl()))
            .satisfies(a ->
                assertThat(a.getCorrectionFileUrlContentType())
                    .as("check correctionFileUrl content type")
                    .isEqualTo(expected.getCorrectionFileUrlContentType())
            )
            .satisfies(a -> assertThat(a.getResponseDate()).as("check responseDate").isEqualTo(expected.getResponseDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJustificationDetailsUpdatableRelationshipsEquals(JustificationDetails expected, JustificationDetails actual) {
        assertThat(actual)
            .as("Verify JustificationDetails relationships")
            .satisfies(a -> assertThat(a.getClassSection()).as("check classSection").isEqualTo(expected.getClassSection()))
            .satisfies(a -> assertThat(a.getJustification()).as("check justification").isEqualTo(expected.getJustification()));
    }
}
