package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModalityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModalityAllPropertiesEquals(Modality expected, Modality actual) {
        assertModalityAutoGeneratedPropertiesEquals(expected, actual);
        assertModalityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModalityAllUpdatablePropertiesEquals(Modality expected, Modality actual) {
        assertModalityUpdatableFieldsEquals(expected, actual);
        assertModalityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModalityAutoGeneratedPropertiesEquals(Modality expected, Modality actual) {
        assertThat(actual)
            .as("Verify Modality auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModalityUpdatableFieldsEquals(Modality expected, Modality actual) {
        assertThat(actual)
            .as("Verify Modality relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModalityUpdatableRelationshipsEquals(Modality expected, Modality actual) {
        // empty method
    }
}
