package com.mycompany.senaattendance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeSlotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeSlotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllUpdatablePropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotUpdatableFieldsEquals(expected, actual);
        assertTimeSlotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAutoGeneratedPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(actual)
            .as("Verify TimeSlot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableFieldsEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(actual)
            .as("Verify TimeSlot relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableRelationshipsEquals(TimeSlot expected, TimeSlot actual) {
        // empty method
    }
}
